//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFB.Web.Reply {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblreplyID;
	protected global::System.Web.UI.WebControls.Label lblfeedbackID;
	protected global::System.Web.UI.WebControls.Label lblreplier;
	protected global::System.Web.UI.WebControls.Label lblreplyText;
	protected global::System.Web.UI.WebControls.Label lblreplyTime;
	protected global::System.Web.UI.WebControls.Label lblnumber;
	protected global::System.Web.UI.WebControls.Label lblisRead;


       
    }
}
